 name: KevReCraftAPI
 version: 1.0.0
 description: This is the official Plugin API for KevReCraft
 author: KevReTV
 api-version: 1.15
 
 main: de.kevrecraft.KevReCraftAPI
 
 commands:
   help:
     description: Shows you all about API Commands.
     usage: Syntax error! Simply type /&lt;command&gt; to show Help.
   perm:
     description: Shows you all about Permissions.
     usage: Syntax error! Simply type /&lt;command&gt; to show Help.